# Blog
keywords: Hexo,HTML,CSS,javascript,iOS,react-native,react,back-end,blog,junso,note,github,hello-acuario,student,china,chongqing,middle school,product,develop
author: junso,wzllxiqirahwl@iCloud.com
description: 😃 It's my own blog, but I gave it a good name, huevo, maybe some colorful eggs of my life here.
avatar: /images/favicon.png

# Social Accounts
twitter: junsoyo
rss: 
weibo: 
instagram: junsoyo
github: hello-acuario
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 
# Valine comments https://valine.js.org
valine:
  enable: true # if you want use valine, please set enable: true
  appid: WgzuYsVSKDgSVjsNNIMV7aAi-gzGzoHsz # your leancloud appid
  appkey: r1tOb4wVhwY51l3KIPuCIcfy # your leancloud appkey
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: write your colorful eggs # comment box placeholder

